## Static configuration
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: dnschallenge
  traefik:
    address: ":9000"
  rabbitmq:
    address: ":8883/tcp"
  takapi:
    address: ":8080/tcp"
  takapisecure:
    address: ":8443/tcp"
    http:
      tls:
        options: ots@file
  takace:
    address: ":8446/tcp"
    http:
      tls:
        certResolver: dnschallenge
  takstreaming:
    address: ":8088/tcp"
  takstreamingsecure:
    address: ":8089/tcp"

certificatesResolvers:
  #dnschallenge:
  #  acme:
  #    storage: /etc/traefik/acme/dnsChallenge.json
  #    dnsChallenge:
  #      # https://doc.traefik.io/traefik/https/acme/#providers
  #      #provider: cloudflare
  #      delayBeforeCheck: "20"
  #      resolvers:
  #        - "1.1.1.1:53"
  #        - "8.8.8.8:53"
  #    caServer: https://acme-staging-v02.api.letsencrypt.org/directory

  httpchallenge:
    acme:
      storage: /etc/traefik/acme/httpchallenge.json
      httpChallenge:
        entryPoint: web
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory

global:
  checkNewVersion: false
  sendAnonymousUsage: false

ping: {}
api:
  insecure: true
  disableDashboardAd: true

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  #level: INFO
  level: DEBUG

accessLog: {}