http:
  serversTransports:
    opentakserver:
      serverName: "opentakserver"
      rootCAs:
        - "/app/ots/ca/ca.pem"

tls:
  options:
    ots-mTLS:
      clientAuth:
        clientAuthType: RequireAndVerifyClientCert
        caFiles:
          - "/app/ots/ca/ca.pem"

  stores:
    default:
      defaultCertificate:
        certFile: "/app/ots/ca/certs/opentakserver/opentakserver.pem"
        keyFile: "/app/ots/ca/certs/opentakserver/opentakserver.nopass.key"

  certificates:
    - certFile: "/app/ots/ca/certs/opentakserver/opentakserver.pem"
      keyFile: "/app/ots/ca/certs/opentakserver/opentakserver.nopass.key"